const gulp = require('gulp');
const jetpack = require('fs-jetpack');
const Jasmine = require('jasmine');

gulp.task('run-e2e', ['environment', 'build-e2e'], () => {
	const srcDir = jetpack.cwd('src');
	const destDir = jetpack.cwd('app');
	
	var jasmine = new Jasmine();
	
	jasmine.execute(['app/e2e.js.autogenerated']);
});